{
 "title": "Main dashboard",
 "time": { "from": "now-4m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cuentas", "label": "Cuentas", "query": "1,2,3,4" },
   { "name": "server", "query": "arVault" },
   {
    "name": "container",
    "query": "exchange_api_1, exchange_api_2, exchange_api_3, exchange_cadvisor_1, exchange_grafana_1, exchange_graphite_1,  exchange_nginx_1, exchange_bbox_1"
   }
  ]
 },
 "panels": [
  {
   "title": "Prueba",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "target": "stats.arVault.response.*" }
   ]
  },
  {
   "title": "Scenario duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "target": "alias(stats.gauges.artillery-api.scenarioDuration.median, 'median')"
    },
    {
     "target": "alias(stats.gauges.artillery-api.scenarioDuration.p90, 'p90')"
    },
    {
     "target": "alias(stats.gauges.artillery-api.scenarioDuration.std, 'std')"
    }
   ]
  },
  {
   "title": "Exchange duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "target": "alias(stats.timers.arVault.exchange.request.duration.mean, 'mean')"
    },
    {
     "target": "alias(stats.timers.arVault.exchange.request.duration.median, 'median')"
    },
    {
     "target": "alias(stats.timers.arVault.exchange.request.duration.upper_90, 'p90')"
    }
   ]
  },
  {
   "title": "ArVault accounts balances",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.arVault.account.$cuentas.balance, -2)"
    }
   ]
  },
  {
   "title": "Volumen de Compra (Buy)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(stats.arVault.volume.*.buy, -2)"
    }
   ]
  },
  {
   "title": "Volumen de Venta (Sell)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(stats.arVault.volume.*.sell, -2)"
    }
   ]
  }
 ]
}